#!/usr/bin/env bash
# Install Elastic Agent + the hardware collector on the Proxmox VE host.
#
# Run this on the Proxmox host itself, as root. It is safe to re-run — the
# agent is uninstalled and re-enrolled, and the collector files are replaced.
#
#   ./install-agent.sh --url https://192.168.1.50:8220 \
#                      --token <enrollment-token> \
#                      --ca ./ca.crt
set -euo pipefail

AGENT_VERSION=9.5.1
URL="" TOKEN="" CA=""

while [[ $# -gt 0 ]]; do
  case $1 in
    --url)     URL=$2;     shift 2 ;;
    --token)   TOKEN=$2;   shift 2 ;;
    --ca)      CA=$2;      shift 2 ;;
    --version) AGENT_VERSION=$2; shift 2 ;;
    -h|--help) sed -n '2,10p' "$0"; exit 0 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

[[ $EUID -eq 0 ]]   || { echo "!! Run as root."; exit 1; }
[[ -n $URL ]]       || { echo "!! --url is required (e.g. https://192.168.1.50:8220)"; exit 1; }
[[ -n $TOKEN ]]     || { echo "!! --token is required"; exit 1; }
[[ -f ${CA:-} ]]    || { echo "!! --ca must point at the ca.crt copied from stack/certs/ca/"; exit 1; }

step() { printf '\n\033[1;34m==> %s\033[0m\n' "$*"; }

# ── Sensor tooling ───────────────────────────────────────────────────────────
step "Installing lm-sensors and smartmontools"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq lm-sensors smartmontools python3 curl >/dev/null

if [[ ! -f /etc/modules-load.d/lm-sensors.conf ]]; then
  # --auto skips the risky probes, which is what you want on a host running
  # VMs — but it also takes the DEFAULT answer to every prompt, and the
  # default for "add these lines to /etc/modules?" is NO. So on its own it
  # detects the chips and then enables none of them, leaving `sensors` with
  # only whatever the kernel autoloaded. Capture the list it prints, persist
  # it, and load it now so no reboot is needed.
  DETECT=$(sensors-detect --auto 2>/dev/null || true)
  MODS=$(printf '%s\n' "$DETECT" | awk '
    /add this to \/etc\/modules/ { want=1; next }
    want && /^#----cut here----$/ { inblk = !inblk; if (!inblk) want=0; next }
    want && inblk && !/^#/ && NF { print }' | sort -u)
  if [[ -n $MODS ]]; then
    { echo "# Generated by install-agent.sh on $(date -Is)"; printf '%s\n' "$MODS"; } \
      > /etc/modules-load.d/lm-sensors.conf
    while read -r m; do [[ -n $m ]] && modprobe "$m" 2>/dev/null || true; done <<< "$MODS"
    echo "   sensor modules loaded: $(printf '%s ' $MODS)"
  else
    echo "   sensors-detect found no extra chips — CPU and NVMe temps only"
  fi
fi
echo "   sensors reports $(sensors -j 2>/dev/null | grep -c '_input' || echo 0) inputs"

# ── Hardware collector ───────────────────────────────────────────────────────
step "Installing the hardware collector"
install -d -m 0750 -o root -g adm /var/log/elastic
install -m 0755 "$(dirname "$0")/hwstats.py"           /usr/local/bin/hwstats.py
install -m 0644 "$(dirname "$0")/elastic-hwstats.service" /etc/systemd/system/
install -m 0644 "$(dirname "$0")/elastic-hwstats.timer"   /etc/systemd/system/
install -m 0644 "$(dirname "$0")/elastic-hwstats.logrotate" /etc/logrotate.d/elastic-hwstats
systemctl daemon-reload
systemctl enable --now elastic-hwstats.timer
systemctl start elastic-hwstats.service
sleep 2
if [[ -s /var/log/elastic/hwstats.ndjson ]]; then
  echo "   collector wrote $(wc -l < /var/log/elastic/hwstats.ndjson) readings"
else
  echo "   !! collector produced nothing — check: journalctl -u elastic-hwstats"
fi

# ── Elastic Agent ────────────────────────────────────────────────────────────
step "Installing Elastic Agent ${AGENT_VERSION}"
if command -v elastic-agent >/dev/null 2>&1; then
  echo "   removing the existing agent first"
  elastic-agent uninstall --force >/dev/null 2>&1 || true
fi

TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT
ARCH=$(dpkg --print-architecture)   # amd64 / arm64
PKG="elastic-agent-${AGENT_VERSION}-linux-$([[ $ARCH == arm64 ]] && echo arm64 || echo x86_64)"
DL="https://artifacts.elastic.co/downloads/beats/elastic-agent/${PKG}.tar.gz"
echo "   downloading ${PKG}.tar.gz"
curl -fsSL --retry 3 -o "$TMP/agent.tar.gz" "$DL" || {
  echo "!! Download failed: $DL"
  echo "   Check the version exists and that this host can reach artifacts.elastic.co."
  exit 1; }
# The 9.x agent tarball carries 80 directory entries whose mode is
# 0o20000000755 — Go's fs.ModeDir bit (1<<31) leaked into the tar header when
# the artifact was built. A mainline kernel masks the junk off (umode_t is 16
# bits) and GNU tar extracts it in silence; some kernels reject that chmod with
# EFAULT instead — QNAP's QTS, hosting this as an LXD container — and tar then
# reports "Cannot change mode ...: Bad address" for exactly those directories
# plus the top-level symlink, and exits non-zero. The download is fine. Retry
# with python, which masks the mode back to the permission bits and does not
# chmod symlinks at all.
extract_agent() {
  local archive=$1 dest=$2
  if tar -xzf "$archive" -C "$dest" 2>"$dest/tar.err"; then return 0; fi
  tail -3 "$dest/tar.err" | sed 's/^/   /'
  echo "   tar could not extract the archive — retrying with python3"
  command -v python3 >/dev/null 2>&1 || apt-get install -y -qq python3-minimal >/dev/null
  rm -rf "${dest:?}/${PKG:?}"
  # filter= landed in 3.12 (and 3.11.4); older versions extract fully-trusted.
  python3 -c 'import sys, tarfile
kw = {"filter": "fully_trusted"} if hasattr(tarfile, "fully_trusted_filter") else {}
with tarfile.open(sys.argv[1]) as tf:
    members = tf.getmembers()
    for m in members:
        m.mode &= 0o7777
    tf.extractall(sys.argv[2], members=members, **kw)' "$archive" "$dest"
}
extract_agent "$TMP/agent.tar.gz" "$TMP" || {
  echo "!! The downloaded archive could not be extracted."; exit 1; }
[[ -x "$TMP/$PKG/elastic-agent" ]] || { echo "!! $PKG/elastic-agent missing from the archive."; exit 1; }

install -d -m 0755 /etc/elastic-agent
install -m 0644 "$CA" /etc/elastic-agent/ca.crt

# --install-servers is required from 9.0 onward: the default "basic" flavor
# ships without the journald dependencies, and the Journald integration then
# silently collects nothing.
"$TMP/$PKG/elastic-agent" install \
  --non-interactive \
  --install-servers \
  --url="$URL" \
  --enrollment-token="$TOKEN" \
  --certificate-authorities=/etc/elastic-agent/ca.crt

step "Done"
elastic-agent status || true
cat <<EOF

The agent is enrolled. In Kibana → Fleet → Agents it should appear within a
minute and pick up the "proxmox-host" policy.

Check data is flowing:
  elastic-agent status
  journalctl -u elastic-agent -f
EOF
